### ISSUE TITLE
https://portal.conp.ca/pipeline?id=zenodo.2602109 MCFLIRT  is "green" (can be run on cbrain) 

### ISSUE THREAD

**Issue by jbpoline** [CONP-PCNO/conp-portal#341] opened 2020-09-24 03:24 UTC
However, when I click on MCFLIRT, CBRAIN capacity in not available

**Comment by cmadjar** [comment] 2020-09-28 14:11
@jbpoline the green on the left side of the tool name does not correspond to the CBRAIN availability. The CBRAIN availability is represented by the `cb` logo on the right side of the screen, which is disabled (greyed out).

Exemple of a tool available on CBRAIN: https://portal.conp.ca/pipeline?id=zenodo.3899496

PS: the green button represents the URL of the tool, which in this case points to the correct URL.

**Comment by cmadjar** [comment] 2020-09-28 14:12
@jbpoline I removed the bug label and put the won't fix label as this is not a bug. Can you close the issue if you are satisfied with the answer?

Thanks!

**Closed** 2020-10-22 21:27 UTC
Labels: wontfix
