### ISSUE TITLE
DatasetStats needs to be linked one-to-one to a Dataset model and dynamically update as actions happen in the portal

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-portal#97] opened 2019-10-02 13:09 UTC
## Purpose
Right now, there is no tie of the Stats to the Datasets, and they are not dynamically updated at all in the portal. 

## Context
The stats should be updatable and validated to actions in the portal.

## Possible Implementation (optional)
We should tie the stats to the Dataset via a one-to-one relationship and add hooks in the portal to updating when actions occur.

**Comment by xlecours** [comment] 2019-10-07 18:18
PR #99 is about the database schema. 
I will work on the second part of the issue now.

**Comment by xlecours** [comment] 2019-12-02 20:49
For now, DatasetStats have been deleted. The information were hardcoded and static. Once this feature is unable, it should be link to one-to-one to a Dataset. 

Leaving this Issue open to remind us that stats about Dataset downloads, likes and watch (whatever that mean) was a desirable feature.

**Comment by xlecours** [comment] 2019-12-12 19:48
Closing. This has become a duplicate of https://github.com/CONP-PCNO/conp-portal/issues/14

**Closed by xlecours** 2019-12-12 19:48 UTC
Labels: enhancement
