### ISSUE TITLE
Download datasets from portal

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-portal#96] opened 2019-10-02 13:07 UTC
## Purpose
We want for users to be able to download datasets that they have authorization to download to be able to do so without additional logins.  Primarily, this is a currant issue for LORIS datasets, but also will need to be addressed for datasets in other platforms (e.g. BrainCode).

## Context
We want for users to not necessarily need to go to other platforms to get the data unless we truly need to.

## Possible Implementation (optional)
For LORIS, quick and dirty, we decided to create a global user that would be used to access data through the portal.

**Comment by xlecours** [comment] 2019-10-07 19:35
@shots47s Should the user be redirected to LORIS? Or should the portal get a copy of the dataset and sent it to the user via HTTP?

**Comment by jbpoline** [comment] 2019-10-07 19:44
In general it would be nice to have a simple download (say a zip file that when unziped looks nice on the disk, eg a la BIDS) - but this may not be easy and for very large datasets (eg preventAD) it may be better to redirect and give access to the DQT. Any thought ?

**Comment by glatard** [comment] 2020-03-11 14:31
See specification in https://github.com/CONP-PCNO/conp-portal/wiki/Data-download-mechanism-from-CONP-portal

**Comment by cmadjar** [comment] 2020-05-20 14:23
Duplicate of #283 so closing

**Closed by cmadjar** 2020-05-20 14:23 UTC
Labels: discussion-required, enhancement
