### ISSUE TITLE
A popup agreeing with the terms of the license

### ISSUE THREAD

**Issue by jbpoline** [CONP-PCNO/conp-portal#185] opened 2020-03-04 18:33 UTC
## Purpose
A popup needs to appear with  "I agree to comply with the terms of the license associated with this dataset" when download is requested (ie when clicking on the dataset title). 

## Context
Necessary for release

**Comment by glatard** [comment] 2020-03-11 14:02
Duplicate of #158.

**Closed by glatard** 2020-03-11 14:02 UTC
Labels: blocking release
